text2 = 'animals, red as their masters’ hair; and around the horses’ legs quarreled the packof lean, nervous possum hounds that accompanied Stuart and Brent wherever theywent. A little aloof, as became an aristocrat, lay a black-spotted carriage dog,muzzle on paws, patiently waiting for the boys to go home to supper.Between the hounds and the horses and the twins there was a kinship deeperthan that of their constant companionship. They were all healthy, thoughtlessyoung animals, sleek, graceful, high-spirited, the boys as mettlesome as the horsesthey rode, mettlesome and dangerous but, withal, sweet-tempered to those whoknew how to handle them.Although born to the ease of plantation life, waited on hand and foot sinceinfancy, the faces of the three on the porch were neither slack nor soft. They hadthe vigor and alertness of country people who have spent all their lives in the openand troubled their heads very little with dull things in books. Life in the northGeorgia county of Clayton was still new and, according to the standards of Augusta, Savannah and Charleston, a little crude. The more sedate and older sectionsof the South looked down their noses at the up-country Georgians, but here innorth Georgia, a lack'
public2 = text2.replace(' ','').replace(',','').replace('.','').replace('’','').replace(';','').replace('-','').lower()
# print(public2)
text1 = 'tojrmPart OneCHAPTER ISCARLETT O’HARA was not beautiful, but men seldom realized it when caughtby her charm as the Tarleton twins were. In her face were too sharply blended thedelicate features of her mother, a Coast aristocrat of French descent, and the heavyones of her florid Irish father. But it was an arresting face, pointed of chin, squareof jaw. Her eyes were pale green without a touch of hazel, starred with bristlyblack lashes and slightly tilted at the ends. Above them, her thick black browsslanted upward, cutting a startling oblique line in her magnolia-white skin—thatskin so prized by Southern women and so carefully guarded with bonnets, veilsand mittens against hot Georgia suns.Seated with Stuart and Brent Tarleton in the cool shade of the porch of Tara, herfather’s plantation, that bright April afternoon of 1861, she made a pretty picture.Her new green flowered-muslin dress spread its twelve yards of billowing materialover her hoops and exactly matched the flat-heeled green morocco slippers herfather had recently brought her from Atlanta. The dress set off to perfection theseventeen-inch waist, the smallest in three counties, and the tightly fitting basqueshowed breasts well matured for her sixteen years. But for all the modesty of herspreading skirts, the demureness of hair netted smoothly into a chignon and thequietness of small white hands folded in her lap, her true self was poorlyconcealed. The green eyes in the carefully sweet face were turbulent, willful, lustywith life, distinctly at variance with her decorous demeanor. Her manners had beenimposed upon her by her mother’s gentle admonitions and the sterner discipline ofher mammy; her eyes were her own.On either side of her, the twins lounged easily in their chairs, squinting at thesunlight through tall mint-garnished glasses as they laughed and talked, their longlegs, booted to the knee and thick with saddle muscles, crossed negligently.Nineteen years old, six feet two inches tall, long of bone and hard of muscle, withsunburned faces and deep auburn hair, their eyes merry and arrogant, their bodiesclothed in identical blue coats and mustard-colored breeches, they were as muchalike as two bolls of cotton.Outside, the late afternoon sun slanted down in the yard, throwing into gleamingbrightness the dogwood trees that were solid masses of white blossoms against thebackground of new green. The twins’ horses were hitched in the driveway, big'
public1 = text1.replace(' ','').replace(',','').replace('.','').replace('’','').replace(';','').replace('-','').lower()
public = (public1 + public2).replace('—','').replace('1','').replace('8','').replace('6','')
for i in range(len(public)):
    if public[i] < 'a' or public[i] > 'z':
        print(public[i])
print(len(public))
print(type(public))
with open('32.txt','w') as f:
    f.write(public)
